---
- hosts: all
  become: true
  become_user: root
  roles:
  - check-variables
  - core
  - yum
  - selinux
  - { role: mysql-55, when: mysql_version == "5.5"}
  - { role: mysql-57, when: mysql_version == "5.7"}
  - memcached
  - php-remove
  - { role: php-55, when: php_version == "5.5" }
  - { role: php-56, when: php_version == "5.6" }
  - { role: php-72, when: php_version == "7.2" }
  - { role: php-73, when: php_version == "7.3" }
  - { role: php-56-zend, when: php_version == "Zend5.6" }
  - { role: php-74, when: php_version == "7.4" }
  - nodejs
  - nginx
  - hosts-file
  - composer
  - shell
