---
- name: Validate PHP version selected
  fail:
    msg: "Invalid PHP Version"
  when:
    - php_version != "5.5"
    - php_version != "5.6"
    - php_version != "7.2"
    - php_version != "7.3"
    - php_version != "Zend5.6"

- name: Validate MySQL version selected
  fail:
    msg: "Invalid MySQL Version"
  when:
    - mysql_version != "5.5"
    - mysql_version != "5.7"